#!/bin/bash
echo "Vue + Truffle + Webpack"

# ensure that truffle is installed
hash truffle 2>/dev/null || { echo >&2 "truffle is not installed. Install with:\n\n  npm install -g truffle"; exit 1; }

# ensure that vue-cli is install
hash vue 2>/dev/null || { echo >&2 "vue-cli is not installed. Install with:\n\n  npm install -g vue-cli"; exit 1; }

# initialize truffle
truffle init

# compile boilerplate contracts
truffle compile

# create vue app from custom template
vue init wilfreddenton/vue-truffle-webpack-template app
